### ISSUE TITLE
iOS memory leak on saveImageDataToLibrary

### ISSUE THREAD

**Issue by EYHN** [rodrigograca31/Canvas2ImagePlugin#16]
I noticed that every time I save a image, the memory usage will increase by about 3mb.

For my use case, it may be a big trouble.

Using `instruments`, the problem seems to be in
`cordova-plugin-canvas2image-updated/Canvas2ImagePlugin.m:26`

I don’t know much about Objective-C and ios, I hope you can help me.

![image](https://user-images.githubusercontent.com/13579374/79220466-9fcdbf00-7e86-11ea-954d-5fc6971f1603.png)

Here is my javascript code:
```js
window.canvas2ImagePlugin.saveImageDataToLibrary(
      function() {
        navigator.notification.alert("saved", console.log);
        canvas.remove();
      },
      function(err) {
        navigator.notification.alert(err, console.log);
        canvas.remove();
      },
      canvas,
      "jpeg" // format is optional, defaults to 'png'
    );
```

Thank you for your work.

**Comment by rodrigograca31** [comment]
Sorry but I personally also dont know Objective-C but seems we need to free the variable that hols the actual image (the one that holds the 3Mb)

**Comment by rodrigograca31** [comment]
Maybe try to remove `autorelease` on this line https://github.com/rodrigograca31/Canvas2ImagePlugin/blob/52ec655ad453043f618a68e339927c9579f3d067/src/ios/Canvas2ImagePlugin.m#L28
and add it here as `[image release];`
https://github.com/rodrigograca31/Canvas2ImagePlugin/blob/52ec655ad453043f618a68e339927c9579f3d067/src/ios/Canvas2ImagePlugin.m#L47-L51

or just add it without removing the `autorelease`? 🤔

I'm just thinking out loud. because it actually says `autorelease` so it should just work....  
but doesnt.... maybe because it has its own "deallocation function" `dealloc`? 🤔

**Comment by EYHN** [comment]
Thanks for your help, I added `[imageData release]` here. No further memory overflows were found.

https://github.com/rodrigograca31/Canvas2ImagePlugin/blob/52ec655ad453043f618a68e339927c9579f3d067/src/ios/Canvas2ImagePlugin.m#L43-L45

**Comment by rodrigograca31** [comment]
That seems to be because we have our own manual deallocation function so it doesnt dealloc by it self so we have to do it manually....

That means we should also release `image` and `imageData` but I dont know enough about memory stuff or Objective C...... I will close the issue for now but hopefully someone with better knoledge will come along and patch this problem.... 

I'm not confidente just doing the same you did for everyone....... I dont know enough to know if it generates other problems....
